server:
  port: 8082
  servlet:
    context-path: /api/accounts

spring:
  application:
    name: ACCOUNT-SERVICE

  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/accountService?createDatabaseIfNotExist=true&useSSL=false
    username: ${db.username:root}
    password: ${db.password:Admin@123}
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    open-in-view: false

  # i18n
  messages:
    encoding: UTF-8
    basename: i18n/messages

  # Hashicorp/Vault
  config:
    import: vault://
  cloud:
    vault:
      scheme: http
      host: localhost
      port: 8200
      authentication: token
      token: vault-root-token
      kv:
        backend: secret
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    filter: true
  packages-to-scan: com.ngocd.microaccountservice